import { Metadata } from "next";
import Image from "next/image";
import React from "react";

export const metadata: Metadata = {
  title: "Blog Knowledge",
  description: "Generated by create next app",
};

const blog = () => {
  return (
    <div className="h-full">
      <div className="w-full bg-[url('/images/Meteor.svg')] h-[400px] flex justify-center items-center">
        <div className="max-w-5xl mx-auto text-center">
          <label className="text-3xl text-white font-medium ">
            Blog For Knowledge
          </label>
          <div className="mt-3">
            <label className="text-white text-xl">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente,
              animi voluptas commodi laboriosam atque unde optio molestiae
              suscipit, accusantium facere quod exercitationem a ad itaque?
              Beatae, tempore? Tenetur, dolores natus.
            </label>
          </div>
        </div>
      </div>
      <div className="w-full grid grid-cols-8 px-8 mb-4">
        <div className="w-[80%] mx-auto mt-10 mb-3 col-span-6">
          <h2 className=" text-3xl border-b-2 pb-3 ">Blog</h2>
          <div className="grid grid-cols-4 gap-10 mt-8 max-w-7xl mx-auto">
            <div className=" rounded-lg shadow-lg">
              <Image
                className="rounded"
                src={"/images/scott-graham-5fNmWej4tAA-unsplash.jpg"}
                width={400}
                height={400}
                alt="img"
              ></Image>
              <h2 className="text-xl font-medium mt-3 px-5">Articles</h2>
              <h4 className="px-5 pb-5">
                Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                Perferendis amet, odio adipisci corrupti sunt tenetur officiis
              </h4>
              <div className="flex justify-end mb-2 mr-4">
                <h2 className="text-md border-b-2 hover:border-y-cyan-600 cursor-pointer">
                  Readmore
                </h2>
              </div>
            </div>
            <div className=" rounded-lg shadow-lg">
              <Image
                className="rounded"
                src={"/images/scott-graham-5fNmWej4tAA-unsplash.jpg"}
                width={400}
                height={400}
                alt="img"
              ></Image>
              <h2 className="text-xl font-medium mt-3 px-5">Articles</h2>
              <h4 className="px-5 pb-5">
                Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                Perferendis amet, odio adipisci corrupti sunt tenetur officiis
              </h4>
              <div className="flex justify-end mb-2 mr-4">
                <h2 className="text-md border-b-2 hover:border-y-cyan-600 cursor-pointer">
                  Readmore
                </h2>
              </div>
            </div>
            <div className=" rounded-lg shadow-lg">
              <Image
                className="rounded"
                src={"/images/scott-graham-5fNmWej4tAA-unsplash.jpg"}
                width={400}
                height={400}
                alt="img"
              ></Image>
              <h2 className="text-xl font-medium mt-3 px-5">Articles</h2>
              <h4 className="px-5 pb-5">
                Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                Perferendis amet, odio adipisci corrupti sunt tenetur officiis
              </h4>
              <div className="flex justify-end mb-2 mr-4">
                <h2 className="text-md border-b-2 hover:border-y-cyan-600 cursor-pointer">
                  Readmore
                </h2>
              </div>
            </div>
            <div className=" rounded-lg shadow-lg">
              <Image
                className="rounded"
                src={"/images/scott-graham-5fNmWej4tAA-unsplash.jpg"}
                width={400}
                height={400}
                alt="img"
              ></Image>
              <h2 className="text-xl font-medium mt-3 px-5">Articles</h2>
              <h4 className="px-5 pb-5">
                Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                Perferendis amet, odio adipisci corrupti sunt tenetur officiis
              </h4>
              <div className="flex justify-end mb-2 mr-4">
                <h2 className="text-md border-b-2 hover:border-y-cyan-600 cursor-pointer">
                  Readmore
                </h2>
              </div>
            </div>
            <div className=" rounded-lg shadow-lg">
              <Image
                className="rounded"
                src={"/images/scott-graham-5fNmWej4tAA-unsplash.jpg"}
                width={400}
                height={400}
                alt="img"
              ></Image>
              <h2 className="text-xl font-medium mt-3 px-5">Articles</h2>
              <h4 className="px-5 pb-5">
                Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                Perferendis amet, odio adipisci corrupti sunt tenetur officiis
              </h4>
              <div className="flex justify-end mb-2 mr-4">
                <h2 className="text-md border-b-2 hover:border-y-cyan-600 cursor-pointer">
                  Readmore
                </h2>
              </div>
            </div>
          </div>
        </div>
        <div className="grid grid-rows-2 gap-3 w-full h-full mb-5 gap-y-16">
          <div className="shadow-xl h-full my-8 rounded-2xl p-3 col-span-2">
            <h2 className="p-3 border-b-2">Least Post</h2>
            <div className="max-w-sm w-full lg:max-w-full lg:flex mt-5 shadow-lg">
              <div
                className=" h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden bg-[url('/images/Meteor.svg')]"
                title="Woman holding a mug"
              ></div>
              <div className=" bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
                <div className="mb-8">
                  <div className="text-gray-900 font-bold text-xl mb-2">
                    Can coffee make you a better developer?
                  </div>
                  <p className="text-gray-700 text-base">
                    Lorem ipsum dolor sit amet, consectetur adipisi
                  </p>
                </div>
                <div className="flex items-center">
                  <h5>9/20/2023</h5>
                </div>
              </div>
            </div>
          </div>

          <div className="shadow-xl h-full rounded-2xl p-3 col-span-2">
            <h2 className="p-3 border-b-2">Catagories</h2>
            <div className="grid grid-cols-3 gap-3">
              <div className="px-3 py-2 bg-slate-500 rounded-full mt-2 ">
                <h4 className="text-white">Knowledge</h4>
              </div>
              <div className="px-3 py-2 bg-slate-500 rounded-full mt-2 ">
                <h4 className="text-white">Knowledge</h4>
              </div>
              <div className="px-3 py-2 bg-slate-500 rounded-full mt-2 ">
                <h4 className="text-white">Knowledge</h4>
              </div>
              <div className="px-3 py-2 bg-slate-500 rounded-full mt-2 ">
                <h4 className="text-white">Knowledge</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default blog;
