"use client";
import { Metadata } from "next";
import Image from "next/image";
import React from "react";
import { useState, useEffect } from "react";
import Link from 'next/link';
import Navbar from "../components/Navbar";

export const metadata: Metadata = {
  title: "Blog Knowledge",
  description: "Generated by create next app",
};

const blog = () => {
  const [data, setData] = useState([]);
  const [postData, setPostData] = useState<any>({});
  const fetchData = async () => {
    try {
      const response = await fetch("/api/post-blog");
      const result = await response.json();
      setData(result);
      let image = result[0].image;
            // Replace backslashes with forward slashes and remove the 'public' prefix
            image = image.replace(/\\/g, '/').replace('public', '');
            setPostData({ ...result[0], image });
      
    } catch (err) {
      console.error("Error fetching data:", err);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  console.log(data)
  return (
    <div className="h-full">
      <Navbar/>
      <div className="w-full bg-[url('/images/Meteor.svg')] h-[400px] flex justify-center items-center">
        <div className="max-w-5xl mx-auto text-center">
          <label className="text-3xl text-white font-medium ">
            Blog For Knowledge
          </label>
          <div className="mt-3">
            <label className="text-white text-xl">
              ให้ความรู้ด้านบัญชี ภาษี และด้านวิชาการต่างๆ
            </label>
          </div>
        </div>
      </div>
      <div className="w-full grid px-8 mb-4">
        <div className="w-[80%] mx-auto mt-10 mb-3 col-span-6">
          <h2 className=" text-3xl border-b-2 pb-3 ">Blog</h2>
          <div className="grid grid-cols-3 gap-10 mt-8 max-w-7xl mx-auto">
            {data.map((post: any) => (
              <div className=" rounded-lg shadow-lg">
                <Image
                  className="rounded"
                  src={postData.image}
                  width={400}
                  height={400}
                  alt="img"
                ></Image>
                <h2 className="text-xl font-medium mt-3 px-5">{post.header}</h2>
                <h4 className="px-5 pb-5" dangerouslySetInnerHTML={{ __html: post.detail.substring(0, 100) }} />

                
                <div key={post.id_blog} className="flex justify-end mb-2 mr-4">
                  <Link href={`/blog/${post.id_blog}`}>
                    <div className="text-md border-b-2 hover:border-y-cyan-600 cursor-pointer">
                      Readmore
                    </div>
                  </Link>
                </div>
              </div>
            ))}

          </div>
        </div>
        
      </div>
    </div>
  );
};

export default blog;